<!DOCTYPE html>
<html>
    <body>

        <h2>JavaScript Errors - Throw and Try to Catch</h2>
        
        <h3>The finally Statement</h3>
        <p>The finally statement lets you execute code, after try and catch, regardless of the result:</p>
        <p>In this example we have written alert as adddlert to deliberately produce an error:</p>
        
        <p>Please input a number between 5 and 10:</p>

        <input id="demo" type="text">
        <button type="button" onclick="myFunction()">Test Input</button>

        <p id="message" style="background-color:Orange;"></p>

        <script>
            function myFunction() {
                var message, x;
                
                message = document.getElementById("message");
                message.innerHTML = "";
                x = document.getElementById("demo").value;
                
                try { 
                    if(x == "")  throw "is empty";
                    if(isNaN(x)) throw "is not a number";
                    x = Number(x);
                    if(x > 10)   throw "is too high";
                    if(x < 5)    throw "is too low";
                }
                catch(err) {
                    message.innerHTML = "Input " + err;
                }
                finally {
                    document.getElementById("demo").value = "";
                }
            }
        </script>
        
    </body>
</html